new_lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tashkilot/', include('tashkilot.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

student/urls.py
from django.urls import path
from student.views import StudentProfileView, StudentHomeworkView, StudentFanView

app_name = 'student'
urlpatterns = [
    path('profile/', StudentProfileView.as_view(), name='profile'),
    path('homework/', StudentHomeworkView.as_view(), name='homework'),
    path('fan/', StudentFanView.as_view(), name='fan')
]

student/models.py
from django.db import models


class Javob(models.Model):
    uyga_vazifa = models.ForeignKey('teacher.UygaVazifa', on_delete=models.RESTRICT)
    oquvchi = models.ForeignKey('tashkilot.Oquvchi', on_delete=models.RESTRICT)
    javob_kuni = models.DateTimeField(auto_now_add=True)
    javob_matni = models.TextField(default=None, null=True, blank=True)
    javob_fayli = models.FileField(default=None, null=True, blank=True)

student/views.py
from django.shortcuts import render
from django.views.generic import View


class StudentProfileView(View):
    def get(self, request):
        return render(request, 'student/profile.html')
    def post(self, request):
        pass


class StudentHomeworkView(View):
    def get(self, request):
        return render(request, 'student/homework.html')
    def post(self, request):
        pass


class StudentFanView(View):
    def get(self, request):
        return render(request, 'student/fan.html')
    def post(self, request):
        pass

templates/student/fan.html
{% extends 'layouts/base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/fan.css' %}">
{% endblock %}

{% block home %}{% url 'student:account' %}{% endblock %}

{% block content %}
    <div class="row mt-3">
        <div class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="card border-0">
                <div class="card-header media d-flex align-items-center border">
                    <div class="media-body d-flex">
                        <h5 class="mx-auto my-auto">Matematika</h5>
                    </div>
                </div>
                <ul class="list-group border-0">
                    <li class="list-group-item w-100 border-bottom d-flex">
                        <a href="#" class="mx-auto"><i class="bi-file-earmark-arrow-down"></i>Darslikni ko'chirib olish</a>
                    </li>
                    <li class="list-group-item w-100 border-bottom d-flex a-bg-mavzu">
                        <span class="mx-auto text-secondary">Kvadrat tenglamani yechish</span>
                    </li>
                    <li class="list-group-item w-100 border-bottom d-flex">
                        <a href="#" class="mx-auto"><i class="bi-file-earmark-arrow-down"></i>Misollar.pdf</a>
                    </li>
                    <li class="list-group-item w-100 border-bottom d-flex a-bg-mavzu">
                        <span class="mx-auto text-secondary">Diskriminat</span>
                    </li>
                    <li class="list-group-item w-100 border-bottom d-flex">
                        <a href="#" class="mx-auto"><i class="bi-file-earmark-arrow-down"></i>Prosolov.pdf</a>
                    </li>
                    <li class="list-group-item w-100 border-bottom d-flex">
                        <a href="#" class="mx-auto"><i class="bi-file-earmark-arrow-down"></i>Ptolomey masalalari.pdf</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/homework.html
{% extends 'layouts/base.html' %}
{% load static %}


{% block home %}{% url 'student:account' %}{% endblock %}

{% block content %}
    <div class="row mt-3">
        <div class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="card">
                <div class="card-header media d-flex align-items-center">
                    <div class="media-body d-flex">
                        <h5 class="mx-auto my-auto">Ona tili</h5>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div>
                                <span class="bg-primary text-white rounded p-2 d-block w-75">Uyga vazifa<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-75">
                                <small class="text-secondary ml-auto">12-mart, 2021</small>
                            </div>
                            <div class="d-flex">
                                <span class="bg-success text-white rounded p-2 w-50 ml-auto mt-2 w-75 d-block">Javob<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-100">
                                <small class="text-secondary ml-auto ml-1">13-mart, 2021</small>
                            </div>
                        </div>
                        <div class="card-footer d-flex">
                            <span>Baholandi: 5</span>
                            <small class="ml-auto text-secondary">13-mart, 2021</small>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div>
                                <span class="bg-primary text-white rounded p-2 d-block w-75">Uyga vazifa<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-75">
                                <small class="text-secondary ml-auto">15-mart, 2021</small>
                            </div>
                            <form>
                                <div class="form-group">
                                    <label for="exampleFormControlTextarea1">Javob matni</label>
                                    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
                                </div>
                                <div class="input-group mb-3">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" id="inputGroupFile01"
                                               aria-describedby="inputGroupFileAddon01">
                                        <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
                                    </div>
                                </div>
                                <div class="d-flex">
                                    <button type="submit" class="btn btn-primary ml-auto">Yuborish</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/student/profile.html
{% extends 'layouts/base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
{% endblock %}

{% block home %}{% url 'student:account' %}{% endblock %}

{% block content %}
    {#    Student info#}
    <div class="a-student-info row mt-3">
        <div class="col-12 text-center">
            <span class="font-weight-bold d-block" style="font-size: 20px">Abdumalikov Tohir</span>
            <small class="text-secondary">6-A sinf</small>
        </div>
        <div class="col-12 d-flex justify-content-around align-items-center">
            <img src="{% static 'img/no_avatar.png' %}" class="a-image-size rounded-circle" alt="">
            <span class="font-weight-bolder">12ta fan</span>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Menyular#}
    <div class="a-menus row mt-3">
        <div class="col-12 d-flex justify-content-around text-center">
            <div class="a-menu border-bottom border-dark d-inline mr-1 pb-2">
                <span class="font-weight-bold">Uyga vazifalar</span>
            </div>
            <div class="a-menu border-bottom d-inline mr-2 pb-2">
                <span>Fanlar</span>
            </div>
            <div class="a-menu border-bottom d-inline mr-2 pb-2">
                <span>Dars jadvali</span>
            </div>
            <div class="a-menu border-bottom d-inline mr-2 pb-2">
                <span>E'lonlar</span>
            </div>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Homeworks#}
    <div class="a-homeworks row mt-3">
        <div class="a-muddat col-12 mb-3 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="media-body d-inline-flex">
                    <h5 class="p-1 my-auto border border-dark">Ertaga (yoki Bugun)</h5>
                </div>
            </div>
        </div>
        <a href="{% url 'student:homework' %}" class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-danger rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Ona tili</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="badge badge-danger">Bajarilmadi</span>
                    </div>
                </div>
            </div>
        </a>
        <a href="{% url 'student:homework' %}" class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-warning rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Matematika</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="badge badge-success">Bajarildi</span>
                    </div>
                </div>
            </div>
        </a>
        <a href="{% url 'student:homework' %}" class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-info rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Tasviriy san'at</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="badge badge-danger">Bajarilmadi</span>
                    </div>
                </div>
            </div>
        </a>
        <a href="{% url 'student:homework' %}" class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-primary rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Fizika</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="badge badge-success">Bajarildi</span>
                    </div>
                </div>
            </div>
        </a>
        <div class="a-muddat col-12 mb-3 text-decoration-none mt-2" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="media-body d-inline-flex">
                    <h5 class="p-1 my-auto border border-dark">Boshqa kunlar</h5>
                </div>
            </div>
        </div>
        <a href="{% url 'student:homework' %}" class="a-homework col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-success rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Ingliz tili</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="badge badge-danger">Bajarilmadi</span>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {#    /////////////////////#}
    {#    Fanlar#}
    <div class="a-fanlar row mt-3" style="display: none">
        <a href="{% url 'student:fan' %}" class="a-fan col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-danger rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Ona tili</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="text-secondary">4ta fayl, 37ta mavzu</span>
                    </div>
                </div>
            </div>
        </a>
        <a href="{% url 'student:fan' %}" class="a-fan col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="a-class d-inline-flex bg-warning rounded-pill text-decoration-none mr-3">
                    <span class="my-auto text-white mx-auto p-2">Matematika</span>
                </div>
                <div class="media-body d-flex">
                    <div class="ml-auto">
                        <span class="text-secondary">8ta fayl, 24ta mavzu</span>
                    </div>
                </div>
            </div>
        </a>
    </div>
    {#    /////////////////////#}
    {#    Dars jadvali#}
    <div class="a-dars-jadvali row mt-3" style="display: none">
        <div class="col-12">
            <div class="accordion" id="accordionExample">
                <div class="card">
                    <div class="card-header" id="headingDushanba">
                        <h2 class="mb-0">
                            <button class="btn-link btn-block text-left text-decoration-none"
                                    style="border: none; background-color: rgba(0, 0, 0, 0)" type="button"
                                    data-toggle="collapse" data-target="#collapseDushanba" aria-expanded="true"
                                    aria-controls="collapseDushanba">
                                Dushanba
                            </button>
                        </h2>
                    </div>
                    <div id="collapseDushanba" class="collapse show" aria-labelledby="headingDushanba"
                         data-parent="#accordionExample">
                        <div class="card-body">
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">8:00 - 8:45</li>
                                <li class="list-group-item w-50">Ona tili</li>
                            </ul>
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">8:50 - 9:35</li>
                                <li class="list-group-item w-50 text-danger">Dars yo'q</li>
                            </ul>
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50 bg-info text-white">9:40 - 10:25</li>
                                <li class="list-group-item w-50">Fizika</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingSeshanba">
                        <h2 class="mb-0">
                            <button class="btn-link btn-block text-left text-decoration-none collapsed"
                                    style="border: none; background-color: rgba(0, 0, 0, 0)" type="button"
                                    data-toggle="collapse" data-target="#collapseSeshanba" aria-expanded="false"
                                    aria-controls="collapseSeshanba">
                                Seshanba
                            </button>
                        </h2>
                    </div>
                    <div id="collapseSeshanba" class="collapse" aria-labelledby="headingSeshanba" data-parent="#accordionExample">
                        <div class="card-body">
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">8:00 - 8:45</li>
                                <li class="list-group-item w-50">Kimyo</li>
                            </ul>
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">8:50 - 9:35</li>
                                <li class="list-group-item w-50">Adabiyot</li>
                            </ul>
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">9:40 - 10:25</li>
                                <li class="list-group-item w-50">Tasviriy san'at</li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-header" id="headingChorshanba">
                        <h2 class="mb-0">
                            <button class="btn-link btn-block text-left text-decoration-none collapsed"
                                    style="border: none; background-color: rgba(0, 0, 0, 0)" type="button"
                                    data-toggle="collapse" data-target="#collapseChorshanba" aria-expanded="false"
                                    aria-controls="collapseChorshanba">
                                Chorshanba
                            </button>
                        </h2>
                    </div>
                    <div id="collapseChorshanba" class="collapse" aria-labelledby="headingChorshanba"
                         data-parent="#accordionExample">
                        <div class="card-body">
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">8:00 - 8:45</li>
                                <li class="list-group-item w-50">Jismoniy tarbiya</li>
                            </ul>
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">8:50 - 9:35</li>
                                <li class="list-group-item w-50">Musiqa</li>
                            </ul>
                            <ul class="list-group list-group-horizontal w-100">
                                <li class="list-group-item w-50">9:40 - 10:25</li>
                                <li class="list-group-item w-50 text-danger">Matematika</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {#    /////////////////////#}
{% endblock %}

{% block js %}
    <script src="{% static 'js/account.js' %}"></script>
{% endblock %}