new_lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tashkilot/', include('tashkilot.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

tashkilot/urls.py
from django.urls import path
from .views import TashkilotRegistrationView, AddGuruhView, AddOqituvchiView, AddOquvchiView, TashkilotdashboardView, \
    AddFanView

app_name = 'tashkilot'
urlpatterns = [
    path('dashboard/', TashkilotdashboardView.as_view(), name='dashboard'),
    path('registration/', TashkilotRegistrationView.as_view(), name='registration'),
    path('guruh/add/', AddGuruhView.as_view(), name='add-guruh'),
    path('fan/add/', AddFanView.as_view(), name='add-fan'),
    path('oqituvchi/add/', AddOqituvchiView.as_view(), name='add-oqituvchi'),
    path('oquvchi/add/', AddOquvchiView.as_view(), name='add-oquvchi')
]

templates/layouts/base.html
{% load static %}
<!doctype html>
<html lang="uz">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>New LMS</title>
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" href={% static 'vendor/bootstrap-icons/bootstrap-icons.css' %}>
    <link rel="stylesheet" href={% static 'vendor/fontawesome/css/all.css' %}>
    {% block css %}{% endblock %}
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-lg-6 offset-lg-3">
            {#    Header#}
            <div class="row">
                <div class="col-12 d-flex mt-2">
                    <div class="a-logo">
                        <a href="{% block home %}{% endblock %}" class="btn btn-primary">Logo</a>
                    </div>
                    <div class="a-chat-logo ml-auto">
                        <a href="#" class="btn btn-primary">Chat</a>
                    </div>
                </div>
            </div>
            {#    /////////////////////#}
            {% block content %}{% endblock %}
        </div>
    </div>
</div>

<script src={% static 'vendor/jquery-3.6.0.js' %}></script>
<script src={% static 'vendor/bootstrap/js/bootstrap.bundle.js' %}></script>
<script src={% static 'vendor/fontawesome/js/all.js' %}></script>
{% block js %}{% endblock %}
</body>
</html>

templates/layouts/forms.html
{% extends 'layouts/base.html' %}


{% block home %}{% url 'tashkilot:dashboard' %}{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-header">Guruh qo'shish</div>
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
                {{ form }}
                <button type="submit" class="btn btn-primary">Qo'shish</button>
            </form>
        </div>
    </div>
{% endblock %}