new_lms/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tashkilot/', include('tashkilot.urls')),
    path('teacher/', include('teacher.urls')),
    path('student/', include('student.urls')),
]

teacher/urls.py
from django.urls import path
from .views import TeacherHomeView, TeacherProfileView, TeacherBaholashView


app_name = 'teacher'
urlpatterns = [
    path('home/', TeacherHomeView.as_view(), name='home'),
    path('profile/', TeacherProfileView.as_view(), name='profile'),
    path('baholash/', TeacherBaholashView.as_view(), name='baholash')
]

teacher/models.py
from django.db import models


class Mavzu(models.Model):
    oqituvchi = models.ForeignKey('tashkilot.Oqituvchi', on_delete=models.RESTRICT)
    guruh = models.ForeignKey('tashkilot.Guruhlar', on_delete=models.RESTRICT)
    mavzu_matni = models.TextField()
    mavzu_sanasi = models.DateTimeField()
    mavzu_fayli = models.FileField(upload_to='uyga-vazifa-fayllar/', default=None, null=True, blank=True)


class UygaVazifa(models.Model):
    oqituvchi = models.ForeignKey('tashkilot.Oqituvchi', on_delete=models.RESTRICT)
    guruh = models.ForeignKey('tashkilot.Guruhlar', on_delete=models.RESTRICT)
    oxirgi_muddat = models.DateTimeField()
    vazifa_matni = models.TextField(default=None, null=True, blank=True)
    vazifa_oyi = models.CharField(max_length=20)
    vazifa_kuni = models.IntegerField()
    muddat_oyi = models.CharField(max_length=20)
    muddat_kuni = models.IntegerField()
    vazifa_fayli = models.FileField(upload_to='uyga-vazifa-fayllar/', default=None, null=True, blank=True)


class Baholar(models.Model):
    oqituvchi = models.ForeignKey('tashkilot.Oqituvchi', on_delete=models.RESTRICT)
    oquvchi = models.ForeignKey('tashkilot.Oquvchi', on_delete=models.RESTRICT)
    fan = models.ForeignKey('main.Sohalar', on_delete=models.RESTRICT)
    javob = models.ForeignKey('student.Javob', on_delete=models.RESTRICT)
    baho = models.IntegerField()

teacher/views.py
from django.shortcuts import render
from django.views.generic import View


class TeacherHomeView(View):
    def get(self, request):
        return render(request, 'teacher/home.html')
    def post(self, request):
        pass


class TeacherProfileView(View):
    def get(self, request):
        return render(request, 'teacher/profile.html')
    def post(self, request):
        pass


class TeacherAddMavzuView(View):
    def get(self, request):
        return render(request, '')


class TeacherBaholashView(View):
    def get(self, request):
        return render(request, 'teacher/baholash.html')
    def post(self, request):
        pass

templates/teacher/baholash.html
{% extends 'layouts/base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'css/chat-baholash.css' %}">
{% endblock %}

{% block home %}{% url 'teacher:home' %}{% endblock %}

{% block content %}
    <div class="row mt-3">
        <div class="a-student col-12 mb-2 text-decoration-none" style="color: black">
            <div class="card">
                <div class="card-header media d-flex align-items-center">
                    <img src="{% static 'img/no_avatar.png' %}" class="mr-3 a-image-size" alt="...">
                    <div class="media-body d-flex">
                        <h6 class="my-auto">Abdumalikov Tohir</h6>
                    </div>
                </div>
                <div class="card-body">
                    <div class="card mb-3">
                        <div class="card-body">
                            <div>
                                <span class="bg-primary text-white rounded p-2 d-block w-75">Uyga vazifa<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-75">
                                <small class="text-secondary ml-auto">12-mart, 2021</small>
                            </div>
                            <div class="d-flex">
                                <span class="bg-success text-white rounded p-2 w-50 ml-auto mt-2 w-75 d-block">Javob<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-100">
                                <small class="text-secondary ml-auto ml-1">13-mart, 2021</small>
                            </div>
                        </div>
                        <div class="card-footer d-flex">
                            <span>Baholandi: 5</span>
                            <small class="ml-auto text-secondary">13-mart, 2021</small>
                        </div>
                    </div>
                    <div class="card mb-3">
                        <div class="card-body">
                            <div>
                                <span class="bg-primary text-white rounded p-2 d-block w-75">Uyga vazifa<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-75">
                                <small class="text-secondary ml-auto">15-mart, 2021</small>
                            </div>
                            <div class="d-flex">
                                <span class="bg-success text-white rounded p-2 w-50 ml-auto mt-2 w-75 d-block">Javob<br>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ab at expedita explicabo facere impedit ipsum odio officiis perferendis porro possimus quaerat quibusdam quidem repellat reprehenderit vel vitae voluptate, voluptatem, voluptatibus.</span>
                            </div>
                            <div class="d-flex w-100">
                                <small class="text-secondary ml-auto ml-1">16-mart, 2021</small>
                            </div>
                            <div class="input-group mt-2">
                                <input type="text" class="form-control" placeholder="Baho..."
                                       aria-label="Recipient's username" aria-describedby="button-addon2">
                                <div class="input-group-append">
                                    <button class="btn btn-outline-primary" type="button" id="button-addon2">Tasdiqlash</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/teacher/home.html
{% extends 'layouts/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href={% static 'css/main.css' %}>
{% endblock %}

{% block content %}
    {#    Rounded classes list#}
    <div class="row a-classes">
        <div class="col-12 mt-2 mb-2">
            <h4 class="font-weight-bold">Sinflar</h4>
        </div>
        <div class="col-12 d-flex">
            <a href="#" class="a-class a-class-size d-inline-flex bg-danger rounded-circle text-decoration-none mr-3">
                <span class="my-auto text-white mx-auto">5-B</span>
            </a>
            <a href="#" class="a-class a-class-size d-inline-flex bg-warning rounded-circle text-decoration-none mr-3">
                <span class="my-auto text-white mx-auto">6-B</span>
            </a>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Menyular#}
    <div class="a-menus row mt-3">
        <div class="col-12 d-flex justify-content-around text-center">
            <div class="a-menu border-bottom border-dark d-inline mr-1 pb-2">
                <span class="font-weight-bold">Ro'yxat</span>
            </div>
            <div class="a-menu border-bottom d-inline mr-2 pb-2">
                <span>Baholash</span>
            </div>
            <div class="a-menu border-bottom d-inline mr-2 pb-2">
                <span>Jurnal</span>
            </div>
            <div class="a-menu border-bottom d-inline mr-2 pb-2">
                <span>Vazifa yuklash</span>
            </div>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Number of students#}
    <div class="row mt-3">
        <div class="a-student-class col-12 mb-3 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <div class="media-body d-inline-flex">
                    <h5 class="p-1 my-auto border border-dark">5-B sinf</h5>
                    <h5 class="p-1 ml-auto my-auto border border-dark">32 students</h5>
                </div>
            </div>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Students list#}
    <div class="a-students row">
        <a href="{% url 'teacher:baholash' %}" class="a-student col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <img src="{% static 'img/no_avatar.png' %}" class="mr-3 a-class-size" alt="...">
                <div class="media-body d-flex">
                    <h6 class="my-auto">Abdumalikov Tohir</h6>
                    <span class="badge badge-success ml-auto">Tekshirildi</span>
                </div>
            </div>
        </a>
        <a href="{% url 'teacher:baholash' %}" class="a-student col-12 mb-2 text-decoration-none" style="color: black">
            <div class="media d-flex align-items-center">
                <img src="{% static 'img/no_avatar.png' %}" class="mr-3 a-class-size" alt="...">
                <div class="media-body d-flex">
                    <h6 class="my-auto">Murodov Kamol</h6>
                    <span class="badge badge-danger ml-auto">Hali tekshirilmadi</span>
                </div>
            </div>
        </a>
    </div>
    {#    /////////////////////#}
    {#    Baholash#}
    <div class="a-baholash row" style="display: none">
        <div class="col-12">
            <button type="submit" class="btn btn-primary">Jurnalga tushirish</button>
        </div>
        <div class="a-enter-date col-12 mt-3">
            <div class="form-row">
                <div class="col">
                    <div class="form-group">
                        <label for="exampleFormControlSelect">Oyni tanlang</label>
                        <select class="form-control" id="exampleFormControlSelect">
                            <option>Mart</option>
                            <option>Fevral</option>
                            <option>Yanvar</option>
                            <option>Dekabr</option>
                            <option>Noyabr</option>
                            <option>Oktabr</option>
                            <option>Sentabr</option>
                        </select>
                    </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="exampleFormControlSelect">Kunni tanlang</label>
                        <select class="form-control" id="exampleFormControlSelect">
                            <option>19</option>
                            <option>17</option>
                            <option>14</option>
                            <option>12</option>
                            <option>10</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
        <div class="a-student-baho col-12">
            <div class="input-group mb-3">
                <a href="{% url 'teacher:baholash' %}" class="media d-flex align-items-center text-decoration-none text-dark">
                    <img src="{% static 'img/no_avatar.png' %}" class="mr-3 a-class-size" alt="...">
                    <div class="media-body d-flex">
                        <h6 class="my-auto">Abdumalikov Tohir</h6>
                    </div>
                </a>
                <div class="input-group-prepend ml-auto">
                    <span class="input-group-text">5</span>
                </div>
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <input type="checkbox" aria-label="Checkbox for following text input">
                    </div>
                </div>
            </div>
        </div>
        <div class="a-student-baho col-12">
            <div class="input-group mb-3">
                <a href="{% url 'teacher:baholash' %}" class="media d-flex align-items-center text-decoration-none text-dark">
                    <img src="{% static 'img/no_avatar.png' %}" class="mr-3 a-class-size" alt="...">
                    <div class="media-body d-flex">
                        <h6 class="my-auto">Murodov Komil</h6>
                    </div>
                </a>
                <div class="input-group-prepend ml-auto">
                    <span class="input-group-text">4</span>
                </div>
                <div class="input-group-prepend">
                    <div class="input-group-text">
                        <input type="checkbox" aria-label="Checkbox for following text input">
                    </div>
                </div>
            </div>
        </div>
        <div class="a-student-baho col-12">
            <div class="input-group mb-3">
                <a href="{% url 'teacher:baholash' %}" class="media d-flex align-items-center text-decoration-none text-dark">
                    <img src="{% static 'img/no_avatar.png' %}" class="mr-3 a-class-size" alt="...">
                    <div class="media-body d-flex">
                        <h6 class="my-auto">Temirov Sanjar</h6>
                    </div>
                </a>
            </div>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Jurnal#}
    <div class="a-jurnal row" style="display: none">
        <div class="a-mavzu-qoshish col-12">
            <div class="card">
                <div class="card-header text-center">Yangi mavzuni qo'shish</div>
                <form>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleFormControlTextarea">Mavzu nomi</label>
                            <textarea class="form-control" id="exampleFormControlTextarea" rows="3"></textarea>
                        </div>
                        <div class="form-group">
                            <label for="sana">Mavzu sanasi</label>
                            <input type="date" class="form-control" id="sana">
                        </div>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="inputGroupFile">
                                <label class="custom-file-label" for="inputGroupFile">Mavzuning fayl ko'rinishi</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex">
                        <button type="submit" class="btn btn-primary ml-auto">Qo'shish</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="a-mavzular col-12 mt-3">
            <ul class="a-mavzu list-group list-group-horizontal">
                <li class="list-group-item w-75">Nyutonning birinchi qonuni</li>
                <li class="list-group-item w-25">12-fevral, 2021</li>
            </ul>
            <ul class="a-mavzu list-group list-group-horizontal">
                <li class="list-group-item w-75">Zichlik</li>
                <li class="list-group-item w-25">10-fevral, 2021</li>
            </ul>
            <ul class="a-mavzu list-group list-group-horizontal">
                <li class="list-group-item w-75">Tezlanish va tezlik</li>
                <li class="list-group-item w-25">7-fevral, 2021</li>
            </ul>
        </div>
    </div>
    {#    /////////////////////#}
    {#    Vazifa yuklash#}
    <div class="a-vazifa-yuklash row" style="display: none">
        <div class="a-vazifa-qoshish col-12">
            <div class="card">
                <div class="card-header text-center">Yangi vazifa qo'shish</div>
                <form>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="exampleFormControlTextarea">Vazifa matni</label>
                            <textarea class="form-control" id="exampleFormControlTextarea" rows="3"></textarea>
                        </div>
                        <div class="form-row">
                            <div class="col">Vazifa sanasini kiriting</div>
                        </div>
                        <div class="form-row">
                            <div class="col">
                                <div class="form-group">
                                    <select class="form-control">
                                        <option>Mart</option>
                                        <option>Fevral</option>
                                        <option>Yanvar</option>
                                        <option>Dekabr</option>
                                        <option>Noyabr</option>
                                        <option>Oktabr</option>
                                        <option>Sentabr</option>
                                    </select>
                                </div>
                            </div>
                            <div class="col">
                                <div class="form-group">
                                    <select class="form-control">
                                        <option>19</option>
                                        <option>17</option>
                                        <option>14</option>
                                        <option>12</option>
                                        <option>10</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="input-group">
                            <div class="custom-file">
                                <input type="file" class="custom-file-input" id="inputGroupFile">
                                <label class="custom-file-label" for="inputGroupFile">Vazifa fayl ko'rinishida</label>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer d-flex">
                        <button type="submit" class="btn btn-primary ml-auto">Qo'shish</button>
                    </div>
                </form>
            </div>
        </div>
        <div class="a-vazifalar col-12 mt-3">
            <ul class="a-mavzu list-group list-group-horizontal">
                <li class="list-group-item w-75">Nyutonning birinchi qonuni</li>
                <li class="list-group-item w-25">12-fevral, 2021</li>
            </ul>
            <ul class="a-mavzu list-group list-group-horizontal">
                <li class="list-group-item w-75">Zichlik</li>
                <li class="list-group-item w-25">10-fevral, 2021</li>
            </ul>
            <ul class="a-mavzu list-group list-group-horizontal">
                <li class="list-group-item w-75">Tezlanish va tezlik</li>
                <li class="list-group-item w-25">7-fevral, 2021</li>
            </ul>
        </div>
    </div>
    {#    /////////////////////#}
{% endblock %}main

{% block js %}
    <script src={% static 'js/main.js' %}></script>
{% endblock %}